--- 
:snmp: 
  :server: 10.0.4.122
:thermostat: 
  :minimum_temp: 16
:sensors: 
  :'660008023078E910': 
    :userbyte1: 1
    :userbyte2: 1
    :name: Bureau
  :'C200080230866410': 
    :userbyte1: 2
    :userbyte2: 2
    :name: Keuken
  :'7400080230ABFA10': 
    :userbyte1: x 
    :userbyte2: x
    :name: x
  :'B50008023097A710': 
    :userbyte1: 4
    :userbyte2: 4
    :main: true
    :name: Emma
  :'38000802308FAD10':
    :userbyte1: 6
    :userbyte2: 6 
    :name: Marie
  :'9A00080230619C10':
    :userbyte1: 7
    :userbyte2: 7
    :name: Achteraan
  :'350008023078B510':
    :userbyte1: 8
    :userbyte2: 8
    :name: Buitenachter
    
